// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package szprotobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type COMMAND int32

const (
	COMMAND_DB_UNKOWN COMMAND = 0
)

var COMMAND_name = map[int32]string{
	0: "DB_UNKOWN",
}
var COMMAND_value = map[string]int32{
	"DB_UNKOWN": 0,
}

func (x COMMAND) String() string {
	return proto.EnumName(COMMAND_name, int32(x))
}
func (COMMAND) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_1f5a8d1843694af1, []int{0}
}

func init() {
	proto.RegisterEnum("szprotobuf.COMMAND", COMMAND_name, COMMAND_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_1f5a8d1843694af1) }

var fileDescriptor_common_1f5a8d1843694af1 = []byte{
	// 78 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2a, 0xae, 0x02, 0x33, 0x92, 0x4a,
	0xd3, 0xb4, 0x24, 0xb8, 0xd8, 0x9d, 0xfd, 0x7d, 0x7d, 0x1d, 0xfd, 0x5c, 0x84, 0x78, 0xb9, 0x38,
	0x5d, 0x9c, 0xe2, 0x43, 0xfd, 0xbc, 0xfd, 0xc3, 0xfd, 0x04, 0x18, 0x92, 0xd8, 0xc0, 0x6a, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x23, 0x8f, 0xb4, 0x3c, 0x00, 0x00, 0x00,
}
