// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package szprotobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Req
type ReqLoginInfo struct {
	Logintype            uint32   `protobuf:"varint,1,opt,name=logintype,proto3" json:"logintype,omitempty"`
	Userid               int64    `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Othertype            uint32   `protobuf:"varint,3,opt,name=othertype,proto3" json:"othertype,omitempty"`
	Faceid               string   `protobuf:"bytes,4,opt,name=faceid,proto3" json:"faceid,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Imei                 string   `protobuf:"bytes,6,opt,name=imei,proto3" json:"imei,omitempty"`
	Machine              string   `protobuf:"bytes,7,opt,name=machine,proto3" json:"machine,omitempty"`
	Operation            string   `protobuf:"bytes,8,opt,name=operation,proto3" json:"operation,omitempty"`
	Nickname             string   `protobuf:"bytes,9,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLoginInfo) Reset()         { *m = ReqLoginInfo{} }
func (m *ReqLoginInfo) String() string { return proto.CompactTextString(m) }
func (*ReqLoginInfo) ProtoMessage()    {}
func (*ReqLoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_8d91a28b033a3fa5, []int{0}
}
func (m *ReqLoginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLoginInfo.Unmarshal(m, b)
}
func (m *ReqLoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLoginInfo.Marshal(b, m, deterministic)
}
func (dst *ReqLoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLoginInfo.Merge(dst, src)
}
func (m *ReqLoginInfo) XXX_Size() int {
	return xxx_messageInfo_ReqLoginInfo.Size(m)
}
func (m *ReqLoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLoginInfo proto.InternalMessageInfo

func (m *ReqLoginInfo) GetLogintype() uint32 {
	if m != nil {
		return m.Logintype
	}
	return 0
}

func (m *ReqLoginInfo) GetUserid() int64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *ReqLoginInfo) GetOthertype() uint32 {
	if m != nil {
		return m.Othertype
	}
	return 0
}

func (m *ReqLoginInfo) GetFaceid() string {
	if m != nil {
		return m.Faceid
	}
	return ""
}

func (m *ReqLoginInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ReqLoginInfo) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *ReqLoginInfo) GetMachine() string {
	if m != nil {
		return m.Machine
	}
	return ""
}

func (m *ReqLoginInfo) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *ReqLoginInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

// Res
type ResLoginInfo struct {
	Code                 int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *ResLoginData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResLoginInfo) Reset()         { *m = ResLoginInfo{} }
func (m *ResLoginInfo) String() string { return proto.CompactTextString(m) }
func (*ResLoginInfo) ProtoMessage()    {}
func (*ResLoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_8d91a28b033a3fa5, []int{1}
}
func (m *ResLoginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResLoginInfo.Unmarshal(m, b)
}
func (m *ResLoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResLoginInfo.Marshal(b, m, deterministic)
}
func (dst *ResLoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResLoginInfo.Merge(dst, src)
}
func (m *ResLoginInfo) XXX_Size() int {
	return xxx_messageInfo_ResLoginInfo.Size(m)
}
func (m *ResLoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResLoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResLoginInfo proto.InternalMessageInfo

func (m *ResLoginInfo) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResLoginInfo) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResLoginInfo) GetData() *ResLoginData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResLoginData struct {
	Nowtime              int64    `protobuf:"varint,1,opt,name=nowtime,proto3" json:"nowtime,omitempty"`
	Userid               int64    `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Svrtoken             string   `protobuf:"bytes,3,opt,name=svrtoken,proto3" json:"svrtoken,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResLoginData) Reset()         { *m = ResLoginData{} }
func (m *ResLoginData) String() string { return proto.CompactTextString(m) }
func (*ResLoginData) ProtoMessage()    {}
func (*ResLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_8d91a28b033a3fa5, []int{2}
}
func (m *ResLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResLoginData.Unmarshal(m, b)
}
func (m *ResLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResLoginData.Marshal(b, m, deterministic)
}
func (dst *ResLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResLoginData.Merge(dst, src)
}
func (m *ResLoginData) XXX_Size() int {
	return xxx_messageInfo_ResLoginData.Size(m)
}
func (m *ResLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_ResLoginData proto.InternalMessageInfo

func (m *ResLoginData) GetNowtime() int64 {
	if m != nil {
		return m.Nowtime
	}
	return 0
}

func (m *ResLoginData) GetUserid() int64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *ResLoginData) GetSvrtoken() string {
	if m != nil {
		return m.Svrtoken
	}
	return ""
}

func (m *ResLoginData) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqLoginInfo)(nil), "szprotobuf.ReqLoginInfo")
	proto.RegisterType((*ResLoginInfo)(nil), "szprotobuf.ResLoginInfo")
	proto.RegisterType((*ResLoginData)(nil), "szprotobuf.ResLoginData")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_login_8d91a28b033a3fa5) }

var fileDescriptor_login_8d91a28b033a3fa5 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x6e, 0x83, 0x30,
	0x10, 0x84, 0x45, 0xf9, 0x09, 0x6c, 0x5a, 0xa9, 0x5a, 0x55, 0x95, 0x15, 0xf5, 0x80, 0x38, 0x71,
	0xa8, 0x38, 0xb4, 0xaf, 0xd0, 0x4b, 0xa5, 0x9e, 0xfc, 0x06, 0x06, 0x4c, 0x62, 0xa5, 0xd8, 0x14,
	0x9c, 0xfe, 0x3d, 0x79, 0x8f, 0x95, 0xd7, 0x21, 0x28, 0x87, 0xdc, 0x66, 0x66, 0x3d, 0x2c, 0xdf,
	0xc2, 0xfa, 0xdd, 0x6c, 0x95, 0xae, 0x86, 0xd1, 0x58, 0x83, 0x30, 0xfd, 0x92, 0xa8, 0x0f, 0x5d,
	0xf1, 0x17, 0xc0, 0x35, 0x97, 0x1f, 0x6f, 0x6e, 0xfc, 0xaa, 0x3b, 0x83, 0x0f, 0x90, 0xd1, 0x5b,
	0xfb, 0x33, 0x48, 0x16, 0xe4, 0x41, 0x79, 0xc3, 0x97, 0x00, 0xef, 0x21, 0x39, 0x4c, 0x72, 0x54,
	0x2d, 0xbb, 0xca, 0x83, 0x32, 0xe4, 0x47, 0xe7, 0x5a, 0xc6, 0xee, 0xe4, 0x48, 0xad, 0xd0, 0xb7,
	0x4e, 0x81, 0x6b, 0x75, 0xa2, 0x91, 0xaa, 0x65, 0x51, 0x1e, 0x94, 0x19, 0x3f, 0x3a, 0xbc, 0x83,
	0xd8, 0x9a, 0xbd, 0xd4, 0x2c, 0xa6, 0xd8, 0x1b, 0x44, 0x88, 0x54, 0x2f, 0x15, 0x4b, 0x28, 0x24,
	0x8d, 0x0c, 0x56, 0xbd, 0x68, 0x76, 0x4a, 0x4b, 0xb6, 0xa2, 0x78, 0xb6, 0xb4, 0x79, 0x90, 0xa3,
	0xb0, 0xca, 0x68, 0x96, 0xd2, 0x6c, 0x09, 0x70, 0x03, 0xa9, 0x56, 0xcd, 0x5e, 0x8b, 0x5e, 0xb2,
	0x8c, 0x86, 0x27, 0x5f, 0xd4, 0x8e, 0x7c, 0x5a, 0xc8, 0x11, 0xa2, 0xc6, 0xb4, 0x1e, 0x3a, 0xe6,
	0xa4, 0xf1, 0x16, 0xc2, 0x7e, 0xda, 0x12, 0x6c, 0xc6, 0x9d, 0xc4, 0x47, 0x88, 0x5a, 0x61, 0x05,
	0x41, 0xae, 0x9f, 0x58, 0xb5, 0xdc, 0xb2, 0x9a, 0xbf, 0xf6, 0x22, 0xac, 0xe0, 0xf4, 0xaa, 0xf8,
	0x5e, 0x76, 0xb8, 0xd4, 0x71, 0x68, 0xf3, 0x65, 0x55, 0xef, 0xd7, 0x84, 0x7c, 0xb6, 0x17, 0x2f,
	0xbb, 0x81, 0x74, 0xfa, 0x1c, 0xfd, 0x99, 0x42, 0x4f, 0x30, 0xfb, 0x33, 0xba, 0xe8, 0x9c, 0xae,
	0x4e, 0xe8, 0xb7, 0x9e, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xc2, 0xdb, 0x6c, 0xfa, 0x01,
	0x00, 0x00,
}
