// Code generated by protoc-gen-go. DO NOT EDIT.
// source: version.proto

package szprotobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Req
type ReqVersion struct {
	Logintype            uint32   `protobuf:"varint,1,opt,name=logintype,proto3" json:"logintype,omitempty"`
	Plattype             uint32   `protobuf:"varint,2,opt,name=plattype,proto3" json:"plattype,omitempty"`
	Gametype             uint32   `protobuf:"varint,3,opt,name=gametype,proto3" json:"gametype,omitempty"`
	Version              uint32   `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqVersion) Reset()         { *m = ReqVersion{} }
func (m *ReqVersion) String() string { return proto.CompactTextString(m) }
func (*ReqVersion) ProtoMessage()    {}
func (*ReqVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_version_58142342c804973d, []int{0}
}
func (m *ReqVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqVersion.Unmarshal(m, b)
}
func (m *ReqVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqVersion.Marshal(b, m, deterministic)
}
func (dst *ReqVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqVersion.Merge(dst, src)
}
func (m *ReqVersion) XXX_Size() int {
	return xxx_messageInfo_ReqVersion.Size(m)
}
func (m *ReqVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqVersion.DiscardUnknown(m)
}

var xxx_messageInfo_ReqVersion proto.InternalMessageInfo

func (m *ReqVersion) GetLogintype() uint32 {
	if m != nil {
		return m.Logintype
	}
	return 0
}

func (m *ReqVersion) GetPlattype() uint32 {
	if m != nil {
		return m.Plattype
	}
	return 0
}

func (m *ReqVersion) GetGametype() uint32 {
	if m != nil {
		return m.Gametype
	}
	return 0
}

func (m *ReqVersion) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// Res
type ResVersionInfo struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *ResVersionData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResVersionInfo) Reset()         { *m = ResVersionInfo{} }
func (m *ResVersionInfo) String() string { return proto.CompactTextString(m) }
func (*ResVersionInfo) ProtoMessage()    {}
func (*ResVersionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_version_58142342c804973d, []int{1}
}
func (m *ResVersionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResVersionInfo.Unmarshal(m, b)
}
func (m *ResVersionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResVersionInfo.Marshal(b, m, deterministic)
}
func (dst *ResVersionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResVersionInfo.Merge(dst, src)
}
func (m *ResVersionInfo) XXX_Size() int {
	return xxx_messageInfo_ResVersionInfo.Size(m)
}
func (m *ResVersionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResVersionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResVersionInfo proto.InternalMessageInfo

func (m *ResVersionInfo) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResVersionInfo) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResVersionInfo) GetData() *ResVersionData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResVersionData struct {
	Curversion           uint32           `protobuf:"varint,1,opt,name=curversion,proto3" json:"curversion,omitempty"`
	Vartitle             string           `protobuf:"bytes,2,opt,name=vartitle,proto3" json:"vartitle,omitempty"`
	Varmessage           string           `protobuf:"bytes,3,opt,name=varmessage,proto3" json:"varmessage,omitempty"`
	Isforce              uint32           `protobuf:"varint,4,opt,name=isforce,proto3" json:"isforce,omitempty"`
	Updateurl            string           `protobuf:"bytes,5,opt,name=updateurl,proto3" json:"updateurl,omitempty"`
	Notifi               *ResNotification `protobuf:"bytes,6,opt,name=Notifi,proto3" json:"Notifi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResVersionData) Reset()         { *m = ResVersionData{} }
func (m *ResVersionData) String() string { return proto.CompactTextString(m) }
func (*ResVersionData) ProtoMessage()    {}
func (*ResVersionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_version_58142342c804973d, []int{2}
}
func (m *ResVersionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResVersionData.Unmarshal(m, b)
}
func (m *ResVersionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResVersionData.Marshal(b, m, deterministic)
}
func (dst *ResVersionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResVersionData.Merge(dst, src)
}
func (m *ResVersionData) XXX_Size() int {
	return xxx_messageInfo_ResVersionData.Size(m)
}
func (m *ResVersionData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResVersionData.DiscardUnknown(m)
}

var xxx_messageInfo_ResVersionData proto.InternalMessageInfo

func (m *ResVersionData) GetCurversion() uint32 {
	if m != nil {
		return m.Curversion
	}
	return 0
}

func (m *ResVersionData) GetVartitle() string {
	if m != nil {
		return m.Vartitle
	}
	return ""
}

func (m *ResVersionData) GetVarmessage() string {
	if m != nil {
		return m.Varmessage
	}
	return ""
}

func (m *ResVersionData) GetIsforce() uint32 {
	if m != nil {
		return m.Isforce
	}
	return 0
}

func (m *ResVersionData) GetUpdateurl() string {
	if m != nil {
		return m.Updateurl
	}
	return ""
}

func (m *ResVersionData) GetNotifi() *ResNotification {
	if m != nil {
		return m.Notifi
	}
	return nil
}

type ResNotification struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Starttime            int64    `protobuf:"varint,4,opt,name=starttime,proto3" json:"starttime,omitempty"`
	Endtime              int64    `protobuf:"varint,5,opt,name=endtime,proto3" json:"endtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNotification) Reset()         { *m = ResNotification{} }
func (m *ResNotification) String() string { return proto.CompactTextString(m) }
func (*ResNotification) ProtoMessage()    {}
func (*ResNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_version_58142342c804973d, []int{3}
}
func (m *ResNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNotification.Unmarshal(m, b)
}
func (m *ResNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNotification.Marshal(b, m, deterministic)
}
func (dst *ResNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNotification.Merge(dst, src)
}
func (m *ResNotification) XXX_Size() int {
	return xxx_messageInfo_ResNotification.Size(m)
}
func (m *ResNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNotification.DiscardUnknown(m)
}

var xxx_messageInfo_ResNotification proto.InternalMessageInfo

func (m *ResNotification) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResNotification) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ResNotification) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ResNotification) GetStarttime() int64 {
	if m != nil {
		return m.Starttime
	}
	return 0
}

func (m *ResNotification) GetEndtime() int64 {
	if m != nil {
		return m.Endtime
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqVersion)(nil), "szprotobuf.ReqVersion")
	proto.RegisterType((*ResVersionInfo)(nil), "szprotobuf.ResVersionInfo")
	proto.RegisterType((*ResVersionData)(nil), "szprotobuf.ResVersionData")
	proto.RegisterType((*ResNotification)(nil), "szprotobuf.ResNotification")
}

func init() { proto.RegisterFile("version.proto", fileDescriptor_version_58142342c804973d) }

var fileDescriptor_version_58142342c804973d = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xb1, 0x4e, 0xeb, 0x30,
	0x14, 0x86, 0x95, 0xb6, 0xe9, 0xbd, 0x3d, 0xa8, 0x05, 0x59, 0x0c, 0x51, 0x41, 0x08, 0x65, 0x62,
	0xca, 0x40, 0x5f, 0x81, 0x85, 0x85, 0xc1, 0x03, 0xbb, 0x9b, 0x38, 0x91, 0xa5, 0xc4, 0x0e, 0xf6,
	0x49, 0x25, 0x10, 0x2f, 0xc0, 0x23, 0xf2, 0x36, 0xc8, 0xc7, 0x4e, 0x13, 0x75, 0xf3, 0x7f, 0x3e,
	0x3b, 0xff, 0xf9, 0x02, 0xdb, 0x93, 0xb4, 0x4e, 0x19, 0x5d, 0xf4, 0xd6, 0xa0, 0x61, 0xe0, 0xbe,
	0xe8, 0x70, 0x1c, 0xea, 0xfc, 0x1b, 0x80, 0xcb, 0x8f, 0xf7, 0xc0, 0xd9, 0x3d, 0x6c, 0x5a, 0xd3,
	0x28, 0x8d, 0x9f, 0xbd, 0xcc, 0x92, 0xc7, 0xe4, 0x69, 0xcb, 0xa7, 0x01, 0xdb, 0xc3, 0xff, 0xbe,
	0x15, 0x48, 0x70, 0x41, 0xf0, 0x9c, 0x3d, 0x6b, 0x44, 0x27, 0x89, 0x2d, 0x03, 0x1b, 0x33, 0xcb,
	0xe0, 0x5f, 0x5c, 0x20, 0x5b, 0x11, 0x1a, 0x63, 0x5e, 0xc3, 0x8e, 0x4b, 0x17, 0xdb, 0x5f, 0x75,
	0x6d, 0x18, 0x83, 0x55, 0x69, 0xaa, 0x50, 0x9e, 0x72, 0x3a, 0xb3, 0x1b, 0x58, 0x76, 0xae, 0xa1,
	0xca, 0x0d, 0xf7, 0x47, 0x56, 0xc0, 0xaa, 0x12, 0x28, 0xa8, 0xe9, 0xea, 0x79, 0x5f, 0x4c, 0x42,
	0xc5, 0xf4, 0xbd, 0x17, 0x81, 0x82, 0xd3, 0xbd, 0xfc, 0x37, 0x99, 0x17, 0x79, 0xc0, 0x1e, 0x00,
	0xca, 0xc1, 0x8e, 0x7b, 0x05, 0xd7, 0xd9, 0xc4, 0x0b, 0x9d, 0x84, 0x45, 0x85, 0xad, 0x8c, 0xcd,
	0xe7, 0xec, 0xdf, 0x9e, 0x84, 0xed, 0xa4, 0x73, 0xa2, 0x09, 0xba, 0x1b, 0x3e, 0x9b, 0x78, 0x61,
	0xe5, 0x6a, 0x63, 0x4b, 0x39, 0x0a, 0xc7, 0xe8, 0x7f, 0xf0, 0xd0, 0x57, 0x02, 0xe5, 0x60, 0xdb,
	0x2c, 0xa5, 0x87, 0xd3, 0x80, 0x1d, 0x60, 0xfd, 0x66, 0x50, 0xd5, 0x2a, 0x5b, 0x93, 0xd8, 0xdd,
	0x85, 0x58, 0x80, 0xa5, 0x40, 0x65, 0x34, 0x8f, 0x57, 0xf3, 0x9f, 0x04, 0xae, 0x2f, 0x18, 0xdb,
	0xc1, 0x42, 0x55, 0x51, 0x6a, 0xa1, 0x2a, 0x76, 0x0b, 0xe9, 0xdc, 0x24, 0x04, 0xbf, 0x66, 0x69,
	0x34, 0x4a, 0x8d, 0xd1, 0x61, 0x8c, 0x7e, 0x4d, 0x87, 0xc2, 0x22, 0xaa, 0x2e, 0x28, 0x2c, 0xf9,
	0x34, 0xf0, 0xef, 0xa4, 0xae, 0x88, 0xa5, 0xc4, 0xc6, 0x78, 0x5c, 0xd3, 0xb6, 0x87, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x07, 0xd2, 0x10, 0xc5, 0x71, 0x02, 0x00, 0x00,
}
